spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 759816068359-c5cac6g92ecrbvqp2slasu01s1l9c45j.apps.googleusercontent.com
            client-secret: ENC(vlsE33bk+dkgD4Bi7WQA9YcMQO6Qs4DjdkymYNw+/iDjq5kGMiBPOwKPjWlg84Rb)
            scope: profile,email

          kakao:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-id: 5dbec63686fc6c4e26b3a9efe6ac8da6
            client-secret: ENC(kRZxItwkzVZuQRsDX5cg2VBpvH20XHsig/kbfzmhvj1ZKYOBfK/PegxbmVTwZzdt)
            client-name: Kakao
            client-authentication-method: POST
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code

          naver:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-id: NOqoJ1yvw73QUBJbdZm9
            client-secret: ENC(WbNZX03VhyVKKa2oFkHbYVHIVHGvGSR/)
            client-name: Naver
            scope: name,email
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


