spring:
  profiles:
    active: prod
    include: oauth
---
spring:
  security:
    filter:
      order: 0
      dispatcher-types: request

  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(tHung8hp8HKf0vVI7PemI1j6wnEkEWkhxLRhgyaDEW+U3BCF5T7Q3SsjeQO8CZyWk1N3cMmhRbYROHTPjjl0T03BraKZr4p00GRRPF+C12uWRtLNDzw/t/MxfkPs1D1RIcV/pOwgBJ3vJ8oxFMS9AMK2QlutuF8u7BPSmjkqQcTtPkEd9HZdbQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shawnlsj09@gmail.com
    password: ENC(ohXZdGb84MhDz1AqaQfs1St14rp82HWEgFo4rUypx2Y=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.bluesky.mainservice: info
    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: false

server:
  servlet:
    session:
      cookie:
        name: __Host-sessionId
  tomcat:
    relaxed-path-chars: <,>,{,},[,],^,`,\,|
    relaxed-query-chars: <,>,{,},[,],^,`,\,|