spring:
  profiles:
    active: prod
    include: oauth
---
spring:
  security:
    filter:
      order: 0
      dispatcher-types: request

  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(bTvgL/lALVRNfl6ZVc2k49ZEtTyE/3L3SrMllpENQe+mCDm2AJwHRvssnsYJU+4rb9UAAr2H7Cgjn+p2Iw46a32az87hTfVYrhH45w9+F27IN3O+yMEDKoQnG7FJSqIIXVtLNs/ZPPZhbztA5R5lNQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shawnlsj09@gmail.com
    password: ENC(ohXZdGb84MhDz1AqaQfs1St14rp82HWEgFo4rUypx2Y=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.bluesky.mainservice: info
    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: false

server:
  servlet:
    session:
      cookie:
        name: __Host-sessionId
  tomcat:
    relaxed-path-chars: <,>,{,},[,],^,`,\,|
    relaxed-query-chars: <,>,{,},[,],^,`,\,|