spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
   org.hibernate.SQL: debug


decorator:
  datasource:
    p6spy:
      enable-logging: true
