spring:
  profiles:
    active: "local"
---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(T5CU1bAIMKpHz62bhGN7ipjo5SgMmv1Bwa6TY6++k6XmaO/g9e25tD3N8DQZTJCLh5lezenm2KuRQYAHilFYXlNnzpnvCCa4byVOYoG8HW1wfc7EJYkXr9H+tFFoiL4PRE99r/++FUQOODhSyTiGBg==)

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: false

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/bluesky
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#h2 설정
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    com.bluesky.mainservice: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true