spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://yhqgalceygxbuy:294b65bafe22dde4742476473205fac16ed4d81d9428973b0c35403959cacbc4@ec2-34-197-84-74.compute-1.amazonaws.com:5432/dcqjtsg7v6te6c


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
   org.hibernate.SQL: debug


decorator:
  datasource:
    p6spy:
      enable-logging: false
